title: Rain
description: SherryAnalytics – writings on data, AI, cloud and reflections
baseurl: "/Rain"
url: "https://sherryanalytics.github.io"

theme: minima

collections:
  garden-of-thoughts:
    output: true
    permalink: /garden-of-thoughts/:name/

defaults:
  - scope:
      path: "garden-of-thoughts"
      type: "garden-of-thoughts"
    values:
      layout: post

header_pages:
  - garden-of-thoughts/index.md
